### ISSUE TITLE
Opening gltf files from cross-origin should be allowed

### ISSUE THREAD

**Issue by sthenyandeni** [larsjarlvik/webgl-gltf#14]
In the `loadModels` function, the image object used to load textures does not have its `crossOrigin` property set to `undefined` or `anonymous` which means that in some cases, opening models from other sites does not work. Allowing this to be possible could as simple as adding the following line after the declaration of the image:

`img.crossOrigin = "undefined";`

**Comment by larsjarlvik** [comment]
I'm currently not actively maintaining this project but are open to receive pull request and publish new versions with fixes if needed.

**Comment by sthenyandeni** [comment]
I have created a pull request #16 that should fix this issue. Please alert me if it unsuitable in anyway.

**Comment by larsjarlvik** [comment]
I have published version 0.3.2 which includes your PR, also updated the dependencies.

Feel free to open a new issue if you find any issues with the new version
