### ISSUE TITLE
why The front is bright, the back is dark

### ISSUE THREAD

**Issue by kt7456** [larsjarlvik/webgl-gltf#33]
![1681272299901](https://user-images.githubusercontent.com/35618730/231346690-d51c93b1-a4ad-4131-a3fc-6290b0892b71.jpg)
![1681272321747](https://user-images.githubusercontent.com/35618730/231346707-8bf5ea25-8e1c-4126-8f9e-f9870030c18a.jpg)

**Comment by larsjarlvik** [comment]
I'm quite sure it's just the lighting setup in the demo that creates this effect.
