### ISSUE TITLE
Some parts missing

### ISSUE THREAD

**Issue by MarioDou** [larsjarlvik/webgl-gltf#6]
I use the code in my project. When I render the gltf with texture, some parts missing .  but ths missing parts are normal when I added to https://gltf-viewer.donmccurdy.com/.
![微信截图_20201221193035](https://user-images.githubusercontent.com/36759314/102772781-11b9b900-43c3-11eb-9f37-8645b288346d.png)
![微信截图_20201221193024](https://user-images.githubusercontent.com/36759314/102772786-13837c80-43c3-11eb-9681-3d27efe8f673.png)

**Comment by larsjarlvik** [comment]
Not sure what's causing it, it could do something with loading multiple meshes in one GLTF file but I haven't seen it myself. Could you upload an example where I can reproduce this issue?

**Comment by MarioDou** [comment]
@larsjarlvik Can u give me your email, I send the gltf model to you.  Thank u

**Comment by larsjarlvik** [comment]
Would like to avoid posting my email (spam). You can create a private GitHub repo and invite me to it if you don't want to share the model publicly.

**Comment by MarioDou** [comment]
@larsjarlvik  I solved this bug.  the mesh node in my .gltf file have more than 1 primitive. but the code only load the first primitive.
